# Configuration for async io system
[asyncIO]
# IO worker executor parallelism
ioWorkerParallelism = -1
# Serializer executor parallelism
serializerParallelism = -1

# Configuration for threaded world generation
[threadedWorldGen]
# Whether to enable this feature
enabled = true
# World generation worker executor parallelism
parallelism = -1
# Whether to allow feature generation (world decorations like trees, ores and etc.) run in parallel
allowThreadedFeatures = false

