# Global settings
[global]

# Configuration for async io system
[asyncIO]
# Serializer executor parallelism
serializerParallelism = -1
# IO worker executor parallelism
ioWorkerParallelism = -1

# Configuration for threaded world generation
[threadedWorldGen]
# Whether to enable this feature
enabled = true
# World generation worker executor parallelism
parallelism = -1
